name: CI/CD Pipeline

on:
  push:
    branches:
      - main # Trigger deployment on push to main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build Docker image
        run: docker build -t tarakesh/mlopsassignment2:latest .

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

      - name: Push Docker image to Docker Hub
        run: docker push tarakesh/mlopsassignment2:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Install SSH client
        run: sudo apt-get install -y ssh

      - name: Decode and set up SSH Key
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" | base64 --decode > ~/.ssh/mlopsassignment2.pem
          chmod 400 ~/.ssh/mlopsassignment2.pem

      - name: SSH and Deploy
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.EC2_PUBLIC_IP }}
          username: ubuntu # Adjust if you're using a different EC2 username
          key_path: ~/.ssh/mlopsassignment2.pem
          script: |
            docker pull tarakesh/mlopsassignment2:latest
            docker stop mlops-container || true
            docker rm mlops-container || true
            docker run -d --name mlops-container -p 5000:5000 tarakesh/mlopsassignment2:latest
