name: Docker Deployment

on:
  push:
    branches:
      - main # Trigger deployment on push to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Install SSH client
        run: sudo apt-get install -y ssh

      - name: Check and create SSH Key
        run: |
          # Ensure the .ssh directory exists
          mkdir -p ~/.ssh

          # Check if the key file already exists
          if [ -f ~/.ssh/mlopsassignment2.pem ]; then
            echo "SSH key already exists."
          else
            echo "SSH key does not exist. Creating it from secrets."
            echo "${{ secrets.EC2_SSH_KEY }}" | base64 --decode > ~/.ssh/mlopsassignment2.pem
            chmod 400 ~/.ssh/mlopsassignment2.pem
          fi

      - name: SSH and Deploy
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.EC2_PUBLIC_IP }}
          username: ubuntu
          key_path: ~/.ssh/mlopsassignment2.pem
          script: |
            # Pull the latest Docker image from Docker Hub
            docker pull tarakesh/mlopsassignment2:latest

            # Stop and remove the existing container if it exists
            docker stop mlops-container || true
            docker rm mlops-container || true

            # Run the new container
            docker run -d --name mlops-container -p 5000:5000 tarakesh/mlopsassignment2:latest
