name: CI/CD Pipeline for Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  # Build Section
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout the code
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Build Docker image with correct architecture
      - name: Build Docker image
        run: docker build --platform linux/amd64 -t tarakesh/mlopsassignment2:latest .

      # Step 5: Log in to Docker Hub
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

      # Step 6: Push Docker image to Docker Hub
      - name: Push Docker image to Docker Hub
        run: docker push tarakesh/mlopsassignment2:latest

  # Deploy Section
  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      # Step 1: Install SSH client (if not already installed)
      - name: Install SSH Client
        run: sudo apt-get install -y openssh-client

      # Step 2: Add SSH private key from GitHub Secret
      - name: Add SSH private key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      # Step 3: SSH into EC2 instance, clean up Docker, and deploy
      - name: SSH and Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
            # Stop and remove existing container (if any)
            docker stop mlops-container || true
            docker rm mlops-container || true
            
            # Remove unused Docker images, containers, and volumes to free space
            docker system prune -af --volumes
            
            # Pull the latest Docker image
            docker pull tarakesh/mlopsassignment2:latest
            
            # Run the container
            docker run -d --name mlops-container -p 5000:5000 tarakesh/mlopsassignment2:latest
          EOF
