name: CI/CD Pipeline for Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout the code
        uses: actions/checkout@v3

      # Step 2: Set up Python environment (if required for testing or building)
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # Step 3: Install dependencies (if needed for building/testing)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Build Docker image
      - name: Build Docker image
        run: docker build -t tarakesh/mlopsassignment2:latest .

      # Step 5: Log in to Docker Hub
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

      # Step 6: Push Docker image to Docker Hub
      - name: Push Docker image to Docker Hub
        run: docker push tarakesh/mlopsassignment2:latest

      # Step 7: Install SSH client (if not already installed)
      - name: Install SSH Client
        run: sudo apt-get install -y openssh-client

      # Step 8: Add SSH private key from GitHub Secret
      - name: Add SSH private key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }} # Store the .pem key as a GitHub secret (not base64 encoded)

      # Step 9: SSH into EC2 instance and deploy Docker container
      - name: SSH and Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
            docker pull tarakesh/mlopsassignment2:latest
            docker stop mlops-container || true
            docker rm mlops-container || true
            docker run -d --name mlops-container -p 5000:5000 tarakesh/mlopsassignment2:latest
          EOF
