name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Install Docker
        run: sudo apt-get install -y docker.io

      - name: Create SSH directory if it doesn't exist
        run: mkdir -p ~/.ssh

      - name: Decode and set up SSH Key
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" | base64 --decode > ~/.ssh/mlopsassignment2.pem
          chmod 400 ~/.ssh/mlopsassignment2.pem
        shell: /bin/bash

      - name: Check if SSH key was created
        run: ls -la ~/.ssh/mlopsassignment2.pem

      - name: SSH and Deploy
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.EC2_PUBLIC_IP }}
          username: ubuntu
          key_path: ~/.ssh/mlopsassignment2.pem
          script: |
            docker pull tarakesh/mlopsassignment2:latest
            docker stop mlops-container || true
            docker rm mlops-container || true
            docker run -d --name mlops-container -p 5000:5000 tarakesh/mlopsassignment2:latest
